GET http://localhost:3000/api/question

###

POST http://localhost:3000/api/question
Content-Type: application/json

{
  "id": 988,
  "question": "How do you round the number 7.25, to the nearest integer?",
  "answers": {
    "answer_a": "Math.round(7.25)",
    "answer_b": "round(7.25)",
    "answer_c": "rnd(7.25)",
    "answer_d": "Math.rnd(7.25)",
    "answer_e": null,
    "answer_f": null
  },
  "category": "Code"
}